### ISSUE TITLE
What is the ```SUBSET``` variable in the config.py ?

### ISSUE THREAD

**Issue by Karthik-Pandaram** [razvancaramalau/Sequential-GCN-for-Active-Learning#10]
Hi can you please tell me what the subset variable in the config.py means. I tried to run the code for cifar10 with an addendum of 100 per cycle and a subset of 100 ( thought it was the initial training dataset size).
When I run CoreGCN with this config, I get an assertions error in the Kcentergreedy algo, on this line shown here.
It would be great if you could help me fix this error.

[`https://github.com/razvancaramalau/Sequential-GCN-for-Active-Learning/blob/master/kcenterGreedy.py#L142C8-L142C8`](url)

**Comment by razvancaramalau** [comment]
Hi the subset is just a pre-sampling randomly a subset of cifar10-100, from which the selection with the budget is applied. This is to overcome the redundancy that may occur for the task. Therefore, you may set the addendum to 100 and keep the subset size to 10000 (out of 49900) unlabelled.
