### ISSUE TITLE
Super adjacency matrix

### ISSUE THREAD

**Issue by lijiaoyang** [razvancaramalau/Sequential-GCN-for-Active-Learning#8]
For large data sets such as Imagenet, when constructing adjacency matrix, the program memory and video memory will explode. Is there any good solution

**Comment by razvancaramalau** [comment]
This is a known limitation for GCNs in general. However, there are a few directions to mitigate this issue. 
The one mentioned in the paper is by creating a random subset of unlabelled < entire unlabelled pool.
Another way is to sub-graph the feature space according to groups of your labelled data. (This one I also had it implemented and it works). Finally, you can look into graph coarsening. There are some more elegant solutions in there.

**Comment by lijiaoyang** [comment]
thanks for your reply!!
about "Another way is to sub-graph the feature space according to groups of your labelled data. ", could you be more specific? Or any example code？

thanks again !!
